[tox]
env_list = py311, py312, py313
isolated_build = true
skip_missing_interpreters = true

[testenv]
extras = dev
commands =
    python -m pytest {posargs} --cov=FasterAPI --cov-report=term-missing --cov-fail-under=85
    python -m mypy FasterAPI
